blank_issues_enabled: false

issue_template:
  - name: "ğŸ Fix"
    description: "ë²„ê·¸ ìˆ˜ì • í…œí”Œë¦¿ì„ ì‚¬ìš©í•˜ì—¬ ë¬¸ì œë¥¼ ë³´ê³ í•˜ì„¸ìš”."
    labels: ["fix"]
    file: fix.yml
  - name: "âœ¨ Feature"
    description: "ìƒˆë¡œìš´ ê¸°ëŠ¥ ì¶”ê°€ë¥¼ ì œì•ˆí•˜ê±°ë‚˜ êµ¬í˜„í•  ë•Œ ì‚¬ìš©í•˜ì„¸ìš”."
    labels: ["feature"]
    file: feature.yml
  - name: "ğŸ”§ Refactor"
    description: "ê¸°ëŠ¥ ë³€ê²½ ì—†ì´ ì½”ë“œ ê°œì„ ì´ í•„ìš”í•  ë•Œ ì‚¬ìš©í•˜ì„¸ìš”."
    labels: ["refactor"]
    file: refactor.yml